name: Jigyasa Grover

description: ML Engineer, Book Author, AI & Open Source Award Winner

avatar: https://avatars.githubusercontent.com/u/9291400?s=460&u=01a3da66cef82594f745c36933e6413d02af04fa&v=4

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: grover.jigyasa1@gmail.com
  facebook: 
  flickr:
  github: jigyasa-grover
  instagram: 
  linkedin: jigyasa-grover
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jigyasa_grover
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: c/JigyasaGrover/playlists
  googleplus: # anything in your profile username that comes after plus.google.com/
  wordpress: jigyasagrover
  spotify: playlist/6vRPsGPE6v2I81NlWkdGiY


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-172999305-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
# version: v3.6

# Jekyll 3 now only supports Kramdown for Markdown		
kramdown:		
  # Use GitHub flavored markdown, including triple backtick fenced code blocks		
  input: GFM		
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting		
  syntax_highlighter: rouge		
  syntax_highlighter_opts:		
    # Use existing pygments syntax highlighting css		
    css_class: 'highlight'

markdown: kramdown

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

theme: jekyll-theme-cayman

repository: jigyasa-grover/jigyasa-grover.github.io

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-jupyter-notebook

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

plugins:
  - jekyll-seo-tag
  - jekyll-twitter-plugin
